# Towards ethical guidelines {.unnumbered}

## S8-PR-001 {.unnumbered}

**(The other) dendroprovenancing: Developing ethical guidelines in dendrochronological research to protect cultural heritage**

Brita Lorentzen^1^

*^1^ Classics and Tree-Ring Laboratory, Cornell University, Ithaca, New York, USA.*


<bel9@cornell.edu>

Dendrochronological dating and dendroprovenancing provide critical information for dating, characterizing, and identifying wooden cultural heritage to aid in their conservation and preservation. Dendrochronological methods can also be usefully combined with other heritage sciences and art historical analyses in forensic applications to detect fraudulent or stolen wooden artwork and movable heritage. Conversely, though, indiscriminate dendrochronological analysis of looted wooden heritage can increase their value—and demand for similar objects—on the antiquities and art markets and therefore encourage further heritage destruction and criminal trafficking. As the advancement of sampling and analysis methods expands the range of wooden heritage available for tree-ring analysis, the dendrochronological community must also critically re-assess and develop ethical guidelines in our laboratories, professional societies, and research publications for analysing wooden cultural heritage, especially with regard to unprovenanced objects (that is: objects whose history of ownership and transmission is unknown) from private collections and for-profit organizations. 

I discuss my efforts to enact such guidelines within my own laboratory and advocate that rather than relying on informal self-monitoring, individual dendrochronological laboratories and professional tree-ring societies should adopt formal, written ethical guidelines regarding sample provenance that are publicly available, similar to those adopted by the radiocarbon community (Hajdas *et al.* 2019). Professional dendrochronological meetings and journals (e.g., *Dendrochronologia* and *Tree-Ring Research*) should also adopt written guidelines for authors considering object provenance in dendrochronological research prior to their presentation or publication.

Hajdas I, Jull AJT, Huysecom E, Mayor A, Renold M-A, Synal H-A, Hatté C, Hong W, Chivall D, Beck L, Liccioli L, Fedi M, Friedrich R, Maspero F, Sava T 2019. Radiocarbon dating and the protection of cultural heritage. *Radiocarbon* 61(5):1133–1134. <https://doi.org/10.1017/RDC.2019.100>

