
## S2-P-005 {.unnumbered}

**Conservation processes of a painted wooden coffin at Saqqara area**

Abdelmoniem M. Abdelmoniem^1^, Naglaa Mahmoud^1^, Wael S. Mohamed^2^

^*1*^ *Conservation Department, Faculty of Archaeology, Fayoum University, Fayoum, Egypt. ^2^ Polymer department, National Research Centre, Dokki, Giza, Egypt.*

[ama63\@fayoum.edu.eg](mailto:ama63@fayoum.edu.eg){.email}

This paper aims to document the conservation processes of a polychrome wooden coffin at Saqqara dating back to the late period. The exterior part of the coffin is decorated with painted layer, while inside it is covered with a layer of the black resin.

The coffin was in a bad condition. It was covered with a thick layer of dust, loosing parts of the painted and gesso layers, as well as other parts of these layers were lost. Some parts were missing from the foot area of the lid coffin. 2D illustrations and 3D modules were made to document the coffin.

The conservation processes of the wooden coffin included mechanical and chemical cleaning, reattachment of the separated parts of the ground layer and painted layers, filling the edge of the painted layer, and consolidating the black resin layer. The materials used for these processes proved to be stable and retrieval by many researchers.

The conservation process included mechanical cleaning using soft brushes, chemical cleaning using ethyl alcohol and water for painted layer and xylene and water for black resin layer, stabilization of the separated gesso layer using Paraloid B72, filling cracks of the gesso layers using glass microballoon with Paraloid B72, and consolidating the painted layer with KlucelE and black resin layer with Nano Paraloid B72.

## S3-P-005 {.unnumbered}

**Preventive conservation of Egyptian wooden statues back to late period displayed at Egyptian textile museum**

Rasha Shaheen^1^, Asmaa Eltobgy^2^

*^1^ Conservation Department, Egyptian Museum, Cairo, Egypt. ^2^ Conservation Department, Manial Palace Museum, Cairo, Egypt.*

<rashashaheen55@yahoo.com>

The Egyptian Textile Museum in Cairo houses many unique pieces of art, dating back to the Pharaonic times, and are prone to damage from climate change. This paper present preventive conservation of wooden statues to protect them from negative impact of climate change to keep the sustainability of these unique artifacts. It is a Statuette of an old man wearing an elaborate cloak over one shoulder that covers his body from neck to mid-calf (looks like Ka-aper statue). His shaven head resembles representations of Egyptian priests. This heavy type of garment also occurs on a relief dating to this period. Late Period, 30th Dynasty, 380 - 343 BC, Abusir, Giza. The piece suffer from the presence of calcified salts on the surface as a result of the bad displaying of the statue, due to the different coefficient of expansion and contraction between different materials. As well as, the wood from the materials absorb moisture from the surrounding environment, which led to the emergence of salts on the surface. The pieces were documented by the digital microscope. The pieces were cleaned mechanically by blower to remove dust and then use soft brushes. The pieces were placed in the humidification chamber to treat dehydration and salts removal. The pieces were consolidated with Paraloid. The pieces were display in especial a showcase for wooden pieces.
