# Session 5: Evidence of timber trade and transport {.unnumbered}

## S5-O-001 (remote) {.unnumbered}

**Short distance log transport in Austria.**

Michael Grabner^1^, Elisabeth Wächter^1^, Sebastian Nemestothy^1^

*^1^ Institute of Wood Technology and Renewable Materials, University of Natural Resources and Life Sciences, Vienna, Austria.*

<michael.grabner@boku.ac.at>

Several studies of log transport showed surprisingly long distances -- for example from the Baltic region to the Netherlands or England. Even inland transport on rivers is described for long distances -- like several hundred kilometres at the river Rhein to the Netherlands. Log transport at the river Danube to the city of Vienna can be more than 500 km in distance. First results of dendro-provenancing of timber sampled in Vienna are available now. There is evidence for long distance transport for example from the rivers Lech and Isar, as well as short distance for example from the rivers Ybbs and Erlauf.

Otherwise, short distance transport as raft is known at the Danube due to historical photographs. In 1943 a 200 m³ raft went from Aggsbach to Tulln -- a distance of about 60 km.

At the church of the city of Klagenfurt (Carinthia) clear rafting marks were found at the roof construction of the tower -- dated to 1737. The larch trees did show slow growth with up to 170 tree rings. Therefore, an alpine site is the most probable provenance.

At the church of Frauenburg (Styria) clear rafting marks in former parts of the roof construction were found (dated to 1256). Interestingly, the church is situated very close to forests with larch trees being part. The building is about 130 m higher elevated than the river Mur, where the rafts are coming from. A transport directly from the forests to the building is possible (even for larch trees) without upward transportation, which would have been the expected method.

There are cases where short distance timber transport can be proven contrary to our expectations.

## S5-O-002 {.unnumbered}

**The internal and external relations of Roman well timbers**

Manuel Broich^1^, Barbara Diethelm^1^, Thomas Frank^2^, Thorsten Westphal^1^, Karl Peter Wendt^3^

*^1^ Laboratory of Dendroarchaeology, Department of Prehistoric Archaeology, University of Cologne, Cologne, Germany. ^2^ Lindlar, Germany. ^3^ Department of Prehistoric Archaeology, University of Cologne, Cologne, Germany.*

<mbroich8@uni-koeln.de>

The question "Which timbers originate from the same tree?" is not only important for chronology building, but also gives insights into (pre-) historic timber economies and construction processes. Against this background, the present paper analyses the tree-ring patterns of roughly 500 timbers from about 60 wooden well boxes of several Roman villae rusticae, excavated due to the open cast lignite mining activities between the cities of Cologne and Aachen in western Germany.

The objective is to assign three aspects: (1) the provenance of the timbers, (2) their common stands/locations and (3) their origin trees and hence to build groups of timbers which were probably cleft from the same tree. Additionally, it will be investigated whether different wooden wells of a single villa rustica or between several villae rusticae were built with timbers from the same tree to analyse (internal) site and cross-site relationships.

Methodically, two statistical techniques ("dendro-allocation" and hierarchical clustering (Ward D2)), are applied to the measured tree-ring width series of the timbers to approach the above goal. Furthermore, for the timbers of two well sheetings the early and latewood width has been recorded. It will examined whether these additional tree-ring parameters can be useful to assign timbers to their common biological origin.

The identification of timbers from a common stand or even stem-identical timbers and their spatial distribution in a well-researched landscape sheds light on the wood economy in the Roman province of Germania inferior. It will help to answer archaeo-economical questions like the volume of timber used to build a wooden construction, wood supply and trade on a (micro-) regional scale or econometric aspects.

## S5-O-003 {.unnumbered}

**Timber rafting on upper Garonne river : from Pyrenean Mountain forests to heritage**

Anh Linh François^1^, Vincent Labbas^2,\ 3^, Camille Fabre^4^, Sylvain Burri^5^

*^1^ ArScan UMR 7041 CNRS-Université Paris 1: Panthéon-Sorbonne, Paris, France. ^2^ Liege University, Liege, Belgium. ^3^ Laboratory of dendrochronology, KIK-IRPA, Brussels, Belgium. ^4^ Centre Roland Mousnier UMR 8596 CNRS-Université Paris IV : Paris-Sorbonne, Paris, France. ^5^ TRACES UMR 5608 CNRS-Université Toulouse Jean Jaurès, Toulouse, France.*

<anhlinh.francois@gmail.com>

In preindustrial Europe, rafting was the main transportation strategy implemented for middle- and long-distance timber trade from Mountain areas to lowlands rural and urban marketplaces. Pyrenees range, well-stocked in forest resources and divided in several river valleys, was particularly conductive to such a trade. On the northern slope, the upper Garonne River basin was used for supplying the regional capital Toulouse and secondary towns in timber and fuel wood at least from the 13th c. onwards as stated by written records. To meet the increased timber demand during the late medieval and modern period men attempted to adapt forest management and exploitation for producing standardized timber products, and to improve the hydrosystems themselves. This paper tackles the issue of timber rafting in the upper Garonne basin from an interdisciplinary perspective, crossing glances of underwater archaeology, dendrochronology and history. The absence of the archaeological object in the form of a raft wreck, need to study the float through its nautical space, its hydrosystem and its river heritage. It aims at 1) revealing the upper Garonne basin socio-economic singularity that mobilizes both forest and lithic resources, 2) analyzing the technical chaîne opératoire and the transportation facilities built along the watercourses, 3) reconstructing the progressive structuring of timber rafting as a socioeconomic activity and 4) its environmental impact on the hydrosystem and forest cover.

## S5-O-004 {.unnumbered}

**Past timber resources in northern Europe: a holistic approach?**

Aoife Daly^1,2^

*^1^ Saxo Institute, University of Copenhagen, Copenhagen, Denmark. ^2^ Dendro.dk, Copenhagen, Denmark.*

<aoife.daly@hum.ku.dk>; <dendro@dendro.dk>

Studying northern European timber remains from key structures from across six centuries has allowed insights into the material evidence for the exploitation of this resource and the trade of timber through time and space. During the ERC-funded project TIMBER, holistic dendrochronology, geochemistry and genetics of timber remains, along with archaeological and historical analysis of key issues, allows the study of details of the sources of timber, the timing of the occurrence of shortage in regions, and whether shortage alone can be cited as the reason for longer distant timber trade and transport.

Planned case studies to answer specific questions were supplemented with study of new discoveries along the way in a mixture of strategy, serendipity and research improvisation.

In this talk I will take a journey through the evidence, building a timeline of what characterises each period and I will narrate the progression of how past people exploited and acquired this essential resource.

The project "Northern Europe's timber resource - chronology, origin and exploitation" (TIMBER) has received funding from the European Research Council (ERC) under the European Union's Horizon 2020 research and innovation programme (grant agreement No. 677152).

## S5-O-005 {.unnumbered}

**Provenance and periods of timber trade from 'the north' to the northern Netherlands, 1600-1900**

Paul Borghaerts^1^

^1^ Borghaerts Houtdatering, Easterein (Friesland), The Netherlands.

<pdata@borghaerts.nl>

For centuries, countless ships from the north of the Netherlands sailed to northern regions for supplies of timber. It started well before 1500 with oak from southern Norway. From 1600 onwards, increasing amounts of pinewood were being imported. The enormous appetite for timber from the rapidly expanding cities like Amsterdam, and the Dutch East India Company, was unprecedented. By 1700, trade in timber from southern Norway was on the wane, so new sources had to be found. Where were these new regions and in which periods did this trade take place?

The Sound Toll Registers are not always clear on this point and at best only indicate the staple ports from which the timber was shipped, but say nothing about where the timber actually originated from.

The farming industry also expanded dramatically after 1600. In the northern Netherlands this led to the construction of large farmsteads built from the same timber from the northern regions. Thousands still exist. Their heavy beams often have a waney edge and provide long measurement series.

By dating 180 of these farmsteads and dozens of churches and townhouses in Friesland through dendrochronology, over two thousand core samples have become available for researching the flows of timber from the northern regions.

At first, the samples only produced floating chronologies, but it soon proved possible to collate a number of new calendars which were calibrated with material from the ITRDB and from colleagues.

As a result, an increasingly clearer picture is emerging of the ever-shifting regions and periods of origin around the Baltic Sea from 1700 onwards.

## S5-O-006 {.unnumbered}

**Sourcing timber in a historic war zone: The South East Scotland Oak Dendrochronology project**

Coralie Mills^1,\ 2^

^1^ Dendrochronicle, Edinburgh. ^2^ School of Earth and Environmental Sciences, University of St Andrews.

<coralie.mills@dendrochronicle.co.uk>

Scotland's internationalist outlook today resonates with a long history of international trade and political relationships, especially with northern Europe and Scandinavia. The famous Lübeck Letter of 1296 from Scotland's guardians William Wallace and Andrew de Moray to the Lübeck and Hamburg authorities asked them to proclaim Scotland was once more open for business. The letter was written at Haddington in south east Scotland, in the 'debateable lands', between the Forth and Tweed rivers, upon which so many wars between Scots and English were fought. The South East Scotland Oak Dendrochronology (SESOD) project, seeking to develop the native Scottish oak tree-ring record for this geographical gap in our reference data, should perhaps have been titled 'Mission Impossible' because the results reveal the massive and early impact of these conflicts on the native timber supply, even in areas close to great medieval Borders woodlands like the Jed and Ettrick Forests.

In SESOD, a reconnaissance phase to locate candidate sites revealed how few oak timber structures survive and, of those selected for analysis, even fewer have proved to contain native oak. As the SESOD project approaches its finale, this paper builds on the individual site results to interpret the impacts of war and instability over many centuries on the timber supply and woodland history in South East Scotland and reflects on how, despite the challenges, this reinforced allegiances between Scotland and her overseas trading partners. SESOD is now giving a voice to these rare historic oak timbers which survived so much turbulence.

## S5-O-007 {.unnumbered}

**Timber as a marine resource: the role of Arctic driftwood in the Medieval North Atlantic**

Dawn Elise Mooney^1^, Élie Pinta^2^, Lísabet Guðmundsdóttir^3^

^1^ Museum of Archaeology, University of Stavanger, Stavanger, Norway. ^2^ Université Paris 1 Panthéon-Sorbonne, UMR8906 Archéologie des Ameriques, Paris, France. ^3^ Department of Archaeology, University of Iceland, Reykjavík, Iceland.

<dawn.e.mooney@uis.no>

The North Atlantic islands of the Faroe Islands, Iceland and Greenland have always been relatively poor in terms of native timber resources, due to their cold climate and exposed topography. Despite this, timber was vital to the material culture of the Norse settlers of these islands, and their needs in this were often met by driftwood. As in Arctic Norway, where trees are also scarce, driftwood use and ownership was prescribed in Medieval law codes. Historical documentary evidence shows wealthy landowners buying up driftwood rights as valuable assets. Even when imported timber was available, there is evidence that in Iceland at least, craftspeople still deemed the local driftwood to be of superior quality. However, this resource was also unstable, and the delivery of driftwood depended on a range of unpredictable factors related to climate and ocean currents. There is also ongoing debate regarding the relative importance of imported timber, which is for example often referenced in the Icelandic sagas. The use of driftwood is difficult to demonstrate through macroscopic, microscopic or (geo-)chemical analysis. Similarities in the microscopic anatomy of boreal wood taxa preclude definitive provenancing through taxonomic analysis, while material traces of immersion in seawater are often either impermanent or ambiguous, especially in archaeological wood remains. This paper presents a "state-of-the-art" of current research on the exploitation of driftwood timber in the Medieval North Atlantic, and explores potential future directions in this field.

## S5-O-008 {.unnumbered}

**Wood exploitation and timber trade on the north-western frontier of the Roman Empire**

Petra Doeve^1^, Silke Lange^2^

^1^ Dendrochronological laboratory at BAAC Archaeology and Building history, 's-Hertogenbosch, The Netherlands. ^2^ BIAX Consult, Biological Archaeology & Environmental Reconstruction, Zaandam, The Netherlands

<p.doeve@baac.nl> - <lange@biax.nl>

The expansion of the Roman Empire and the military occupation of north-western Europe during the first centuries AD left a mark on the landscape, especially in the province of Germania Inferior nowadays parts of the Netherlands. The south bank of the Rhine became the empire's boundary (limes) and the river flow became the main artery for the supply of goods and troops.

The upsurge in timber demand to construct the many roads, bridges, watch towers and forts (castella) along the limes exceeded the Dutch natural resources. Timber was imported from the empires hinterland in Belgica (Belgium) and Germania Superior (west parts of Germany). As a result, the Dutch Delta is a treasure trove for tree-ring data.

Various sections of the east-to-west orientated limes road are excavated over the past decennia. Recently a new section came under investigation in the coastal region near Leiden and offered a chance to conduct a major dendrochronological study based on a predesignated samples strategy focusing on a representative selection of the timbers, rather than a selective sample strategy aimed to simply date the structure.

In total 141 oak foundation posts were measured from the road which was constructed under the rule of the emperor Hadrianus in AD 125. This paper presents the current understanding of timber trade along the limes and highlights the new results from this recent study. Large-scale sampling for dendrochronological research combined with research into wood use has led to new insights into logging practices and wood exploitation.

## S5-O-009 {.unnumbered}

**Early evidence for timber trade marks on a large Roman quay found in the SE of the City of London**

Damian M Goodburn^1^

^1^ Museum of London Archaeology, London, England.

<futtock.goodburn@gmail.com>

Excavations on the historic City of London waterfront, just west of the Tower of London, revealed the remains of a large oak quay built in AD133. The recent detailed 'forensic' recording produced much new information not recorded during the earlier, limited excavation in 1973. Tree ring dating was refined, and new evidence of the very unusual systems of timber preparation used for many repetitive quay elements were also recorded. However, for this conference one of the most important features were numerous sets of stamped and branded marks which must be associated with the Roman timber trade and supply system. It is likely that this particularly tall quay was built for the use of deep sea trading vessels.

## S5-O-010 {.unnumbered}

**Timber imports to Norse Greenland. Lifeline or luxury?**

Lísabet Guðmundsdóttir^1^

*^1^ Department of Archaeology, University of Iceland, Reykjavík, Iceland.*

<lig5@hi.is>

Due to limited native woodland in Greenland, which was not suitable for larger construction and boatbuilding, it has been argued that it was necessary to import timber to meet the wood requirements of the Norse Greenlanders (985-1450 AD). To evaluate the extent of timber imports to Norse Greenland, the taxonomic composition of archaeological wood assemblages from five Norse sites were analysed to determine whether the wood was native, import or driftwood. The low species diversity of Greenlandic woodlands makes it easy to identify non-native wood remains. However, due to the vast distribution of certain tree species, wood taxa analysis alone cannot differentiate between imported wood and driftwood. As of yet, various chemical methods have not proven to be successful in distinguishing between these two categories. However, by comparing the results with wood assemblages from other cultural groups in Greenland and the Smith Sound, which had limited or no contact with Europeans, I propose that it is possible to estimate the proportions of timber import to Norse Greenland. In this talk I will discuss the importance of timber imports for the Norse Greenlandic society. I will examine the origin of imported timber and whether it was a resource to which everyone had equal access. I will also explore the idea that a lack of imported timber played a part in the abandonment of the Norse Greenlandic settlements.

## S5-O-011 {.unnumbered}

**The production of barrels and casks in the Netherlands in Late Middle Ages and Early Modern period**

Jeroen Oosterbaan^1,2^ , Petra Doeve^3^

^1^ Department of World Archaeology, Faculty of Archaeology, Leiden University, Leiden, the Netherlands. ^2^ Saxion University of Applied Sciences, Deventer, the Netherlands. ^3^ BAAC Archeologie en bouwhistorie, 's-Hertogenbosch, the Netherlands.

<j.oosterbaan@arch.leidenuniv.nl> - <p.doeve@baac.nl>

The northern part of the Low Countries developed into one of the most urbanized regions in Europe in the Late Middle Ages and Early Modern period, with trade as the main source of the development. In this region ports and cities evolved to the main trade hubs of Europe, where both trade and craft flourished.

Barrels and casks were essential to this development since merchandise such as wine, beer, herring were transported in this packing material. During archaeological research these barrels and casks are often found, in both maritime and urban archaeological contexts. Although archaeological reports document these finds accurately, they focus on the use phase as packing material or on the reuse phase as a shaft of a cesspit or water well. The studies pay little attention to the production phase of these wooden vessel by coopers.

This paper explores the way the production of barrels and casks was organized and executed in the late medieval and early modern northern part of the Low Countries. Specific features of the organization of this production can be extracted from the archives of the coopers\' guilds. Archaeological data offers a chance to explore the long-term development of the coopers' craft, by mapping the dendrochronologically established felling dates and the provenance of the timber through time. This is compared with the spatial distribution of the barrels and casks from archaeological context in order to take the first steps in understanding the production of this packaging material.

## S5-O-012 {.unnumbered}

**From research on timber supply in rural areas to regional watersheds**

Vincent Labbas^1,2^, Sarah Cremer^2^, Pascale Fraiture^2^, Patrick Hoffsummer^1^, Christophe Maggi^2^, Armelle Weitz^2^

*^1^ Liege University, Liege, Belgium. ^2^ Laboratorary of dendrochronology, KIK-IRPA, Brussels, Belgium.*

<vincent.labbas@univ-tlse2.fr> - <vincent.labbas@kikirpa.be>

The project Deep in Heritage (FED-tWIN2020-prf024, BELSPO), led by the dendro laboratories of the Royal Institute for Cultural Heritage (KIK-IRPA) and of the ULiège in collaboration, aims to create a common and cooperative tool for dendrochronologists in Belgium. The objective is to re-evaluate the data acquired over the last 40 years by the several laboratories in order to widen the field of possibilities on the provenance of ancient timber. In the context of my research conducted in the southern and eastern mountains (Alps, Pyrenees, Carpathians) between 2010 and 2021 (Aix-Marseille University, laboratories TRACES UMR 5608 and GEODE UMR 5602), the same questioning also arose. Studies on more than 150 rural buildings have revealed processes of wood selection and choice of cutting sites through the joint approach of dendrochronological (more than 1100 tree-ring series), archaeological, archival and ethnographic sources. In addition, this research makes it possible to understand part of the circulation of timber on a local scale upstream of larger-scale commercial circuits.

The methods used and the results obtained within the framework of this « mountain research » will lead to a re-interrogation of timber supply between the Meuse and Seine watersheds and will contribute to the creation of tools for modelling the provenances and terroirs of origin of the wood.

## S5-O-013 (+ poster?) {.unnumbered}

**MARKS ON ART database: forest marks on paintings and sculpture, 1300-1700**

Marieke van Vlierden^1,2^, Seppe Roels^2,\ 3^, Michael Rief^4^

^1^ Independent art historian, Utrecht, The Netherlands. ^2^ associated researcher MARKS ON ART database, RKD -- Netherlands Institute for Art History, The Hague, The Netherlands. ^3^ Independent conservator-restorer of polychrome sculpture, Malines, Belgium. ^3^ Manager ad interim and Head of Collections Suermondt-Ludwig-Museum, Aachen, Germany.

<info@mariekevanvlierden.nl>

The RKD -- Netherlands Institute for Art History has been developing the MARKS ON ART database in close cooperation with the two specialists who devised it, art historian Marieke van Vlierden and conservator-restorer Seppe Roels. The purpose of this new database, which will become accessible online in due course, is to gather and share detailed information on a range of different marks that can be found on sculptures, furniture and the backs of panel paintings, dating from 1300 to 1700.

Besides the more commonly encountered marks -- signatures, monograms, master\'s marks, quality control marks and panel maker's marks which provide unique information about such things as the maker, when and where the object was produced, -- the MARKS ON ART database also includes so-called forest marks. Those large marks are exclusively found on Baltic wainscot, for example on the backs of panel paintings, sculptures, retables and pieces of furniture. They are probably marks of the owner of the forest or the wood (timber) merchant. Created or added in an early stage of processing the basic raw material, the above mentioned marks provide unique information about the trade and transportation of the wood of which the works of art are made.

35 forest marks have been documented so far in MARKS ON ART database. In the presentation we will give an introduction to these marks (Rief) and zoom in on the 10 marks found on the back of an Antwerp retable with the Youth and Passion of Christ in M-Museum, Louvain, dated c. 1520-1525 (Roels/Van Vlierden).

## S5-P-001 {.unnumbered}

**Dendro @ the graveyard. Wood and tree-ring analysis on medieval coffins from Ypres (c. 1200 -- 1400 CE)**

Kristof Haneca^1^, Koen De Groote^1^

^1^ Flanders Heritage Agency, Brussels, Belgium.

<Kristof.Haneca@vlaanderen.be>

In the centre of the medieval city of Ypres a graveyard was unearthed (field campaign 2017-2018), and over 1075 inhumation burials recorded. Many of the deceased were buried in wooden coffins, a considerable number of which have been very well preserved. As the stratigraphy of the graveyard does not allow to accurately reconstruct the chronology and expansion of the burial site, an intensive dendrochronological survey was set-up in order to date the wooden coffins.

Most coffins were made exclusively of oak, although for some the lid was made of poplar/willow. In rare cases beech, elm or alder was used. In total 735 samples were analysed, resulting in 383 unique tree-ring series of which 242 series could be dated (124 remain undated). These dates allowed to precisely date the construction of 84 coffins and revealed that the site was in use as a burial site from c. 1200 CE onwards, which seems to correspond to the oldest phase of the Saint-Nicolas' Church. Around c. 1375 CE, burials ended quite abruptly on this graveyard. For the construction of the coffins imported, high-quality timbers were used. Provenance analysis indicates that wainscot oak boards originate from the Southern Baltic or NW Germany. Very few timbers from local forests were used for the production of the coffins, what might indicate that a rather privileged class was buried on this graveyard.

More in-depth analysis will confront the dendrochronological dataset with the bio-anthropological examination of the skeletal remains and the archaeological data in order to refine the interpretation of the burial site and the medieval population buried at the graveyard.