# (PART\*) ABSTRACTS {-}

# Session 1: Forest history {.unnumbered}

## S1-O-001 {.unnumbered}

**Exploring the significance, acquisition and use of wooden resources
between Norse Greenland and North America: a (re)examination of literary
and archaeological sources**

Elie Pinta^1^

^1^ Université Paris 1 Panthéon-Sorbonne, Paris, France -- UMR 8096.

[Elie.Pinta\@etu.univ-paris1.fr](mailto:Elie.Pinta@etu.univ-paris1.fr){.email}

Since prehistoric times, archaeological data reveal that wherever
forests are to be found, wood and timber are used to make furniture, to
construct buildings and ways of transportation, or as a fuel source.
While forestry practices, woodworking strategies or fuel gathering can
be studied through the archaeological records, historical documents are
also filled with information regarding the significance, acquisition,
and use of wooden resources. For example, much of the Scandinavian
peninsula was forested during the medieval period when Vikings, and the
later Norse, made the exploitation and transformation of wood and timber
one of their most distinguished crafts. Even during their migrations
across the tree-poor North Atlantic islands, Norse settlers kept relying
heavily on wooden materials for everyday use. Around AD 1000, as stated
in the so called Vínland Sagas, and supported by the findings at L'Anse
aux Meadows in northern Newfoundland, the Greenlandic Norse explored
part of the North American Atlantic coast, another heavily forested
area. Having been recognized as partly fictional, the Sagas - as well as
other literary descriptions -- can sometimes be treated with caution
regarding their historical accuracy. However, they also are filled with
ecological descriptions and technical information regarding the
exploitation of resources. Furthermore, archaeological data is sometimes
scarce or difficult to interpret due to methodological limitations.
Confronting both the textual and archaeological data provides a more
comprehensive understanding of wood culture in the Norse Greenlandic
world.

## S1-O-002 {.unnumbered}

**Reconstruction of economic resources associated with timber building
architecture in early medieval urban Trondheim**

Anna Helena Petersén^1^

^1^ Norwegian Institute for Cultural Heritage (NIKU), Trondheim, Norway.

[anna.petersen\@niku.no](mailto:anna.petersen@niku.no){.email}

Timber buildings form a substantial part of the built environment in
medieval Scandinavia, both in rural and urban contexts. Because of often
favorable preservation conditions for organic material in urban
contexts, architectural remains are often encountered in the excavated
archaeological material from Norway's medieval towns. The past building
heritage can be reconstructed using archaeological sources,
cultural-historical information and expertise found in traditional
timber craftsmanship. Analyses of the volume of timber utilised in
buildings in urban contexts, and the types and development of
construction techniques used are important factors to be considered in
discussions of what an urban economy in medieval Norway consisted of.
However, timber as a natural resource is seldom included in studies of
urban medieval economy from an archaeological perspective. This
presentation uses the secular wooden architecture in early medieval
Trondheim (AD 950-1150) as a case to illustrate timber's role as an
economic resource, and highlights aspects of the socioeconomic
organisation the early urban Trondheim retrieved from remains of the
secular wooden architecture regarding access to timber, volumes of
timber used, and types of labour and skills employed.

## S1-O-003 {.unnumbered}

**A dendroecological reconstruction of forest management history in
Mediterranean *Abies pinsapo* forests**

Linar Akhmetzyanov1, Raúl Sánchez-Salguero1, Pablo Casas-Gómez1, Víctor
Lechuga2, Benjamín Viñegla2, J. Julio Camarero3, José I. Seco1, José R.
Guzmán Álvarez4, José A. Carreira2, Juan C. Linares1

1 DendrOlavide, Depto. de Sistemas Físicos, Químicos y Naturales,
Universidad Pablo de Olavide, Sevilla, Spain. 2 Departamento de Biología
Animal, Vegetal y Ecología, Universidad de Jaén, Jaén, Spain. 3Instituto
Pirenaico De Ecología, Consejo Superior de Investigaciones Científicas
(IPE-CSIC), Zaragoza, Spain. 4 Dirección General del Medio Natural,
Biodiversidad y Espacios Protegidos. Consejería de Agricultura,
Ganadería y Desarrollo Sostenible. Junta de Andalucía, Sevilla, Spain.

[lakh\@upo.es](mailto:lakh@upo.es){.email}

Past disturbances related to forest-use history remain poorly understood
in long-term related Moroccan and Spanish fir forests. Here we
investigated tree recruitment, growth trends and abrupt changes in
tree-ring series of old-living trees since early 17th century in four
representative stands: Abies pinsapo in Grazalema and Sierra de las
Nieves (Spain) and A. marocana and A. tazaotana in Talassemtane
(Morocco). Retrospective dendrochronological analyses were supported by
documentary sources reporting changes in forest management and land-use
during the past 300 years. Age structures of each site were
discontinuous in time and revealed different cohorts distributed in
even-aged aggregated patches. Our results showed growth releases related
to past logging during the 18th, 19th and the early 20th century in
Spain and Morocco. Limited tree establishment from the 1940s to 1960s
agreed with intense herd grazing in Spain. Land-use changes leading to
grazing and logging limitations resulted in forest encroachment. The
observed patterns in growth releases allowed us to identify synchronous
past radial-growth releases due to forest management. Tree-ring series
have shown lower sensitivity to external disturbances, due to strong
drought susceptibility of Abies pinsapo, reflected in "blue data". Past
intensive selective cutting of the fir forest might also be reflected in
local historical buildings, opening new perspectives for
dendroarchaeological studies in the area.

## S1-O-004 {.unnumbered}

**Wood for funerary pyres in Barcino (Barcelona, NE Iberian Peninsula):
investigating cremation structures in two necropolis (1st-3rd centuries
CE) starting from charcoal analysis**

Sabrina Bianco1,2, Ethel Allué1,3, Santiago Riera Mora4, Emiliano
Hinojo5, Carme Miró Alaix6

1 Catalan Institute of Human Paleoecology and Social Evolution
(IPHES-CERCA), Tarragona, Spain. 2 Department of History and
Archaeology, Faculty of Geography and History, University of Barcelona,
Barcelona, Spain. 3 Department of History and Art History, University
Rovira and Virgili, Tarragona, Spain. 4 Seminaris d'Estudis i Recerques
Prehistòriques research group (SERP), Department of History and
Archaeology, Faculty of Geography and History, University of Barcelona,
Barcelona, Spain. 5 Freelance archaeologist, Barcelona, Spain. 6
Archaeological Service of Barcelona, responsible of Pla Bàrcino,
Direcció de Memòria, Història i Patrimoni -- Institut de Cultura (ICUB),
Barcelona, Spain.

[sbianco\@iphes.cat](mailto:sbianco@iphes.cat){.email}

Funerary rituals were an important part of the Roman cultural identity,
as they represent, with a precise set of rules and practices, the
passage from the world of livings to the deads. In this sense, fire
played a significant role, as a mean for cleansing the body and the soul
of the deceased through cremation, as well as for cooking funerary
banquets and offers. As consequence of the carbonization process, it is
possible to study the wood used for building the pyre and other goods
placed in the stake (rogus), as for example funerary beds (lecta
funebres), through wood charcoal analysis. In this work, the wood used
for cremations and funerary banquets in two suburban necropolis of the
colony of Barcino (Barcelona) will be discussed and compared. The first,
in use during the 1st century CE, was unearthed under St. Antoni Market,
in relation with a main road (Via Augusta) that entered the roman city
from the west. It counted with several funerary enclosures where 2 busta
and 9 ustrina were identified. A second necropolis, functioning between
the 2nd-3rd centuries CE along another road, was excavated in Vila de
Madrid square, northwest from the city. In this case charcoal proceeding
from cremations (less abundant, as the practice decresed after the 2nd
century CE) or banquets, and two circular charred wooden structures have
been studied. Results of this investigation are significant because they
constitute the first sistematic study of wood use in roman funerary
contexts of Barcelona, up to now very limited to a few fragments.
Furthermore, this work evaluates wood selection practices based on
symbolic, functional or convenience criteria, the presence of wooden
objects/furnitures in the pyre and in general sheds light on the wood
management for supplying these rituals.

## S1-O-005 {.unnumbered}

**Woody resources and their management during Iron Age in northwest
Iberia**

María Martín-Seijo1

1 Departamento de Ciencias Históricas, Universidad de Cantabria,
Edificio Interfacultativo. Avda. de los Castros 52, 39005, Santander,
Spain.

[maria.martin\@unican.es](mailto:maria.martin@unican.es){.email}

Charcoal is the most common archaeobotanical remain recovered from
archaeological contexts dated to Iron Age in northern Iberia. This
presentation will summarise the results obtained from several
case-studies dated to the Iron Age in the northern part of the Iberian
Peninsula. Up to now, many charcoals have been analysed providing an
excellent opportunity to test the possibilities of going beyond
taxonomic identification. In our research we have systematically
combined charcoal analysis in tandem with registering dendrological and
taphonomic attributes. This has provided information to better
characterise the kind of woody resources managed, the combustion
process, the depositional and post-depositional processes affecting to
archaeobotanical assemblages. But it has also been obtained information
about wood uses, woodland management practices, and even about the
relationship established between people and their environment.

## S1-O-006 {.unnumbered}

**Sorting the trees: new evidences of woodland management at La Draga
(Banyoles, Spain)**

Oriol López-Bultó1, Patrick Gassmann2, Ingrid Bertin1, Raquel Piqué1

1 Department of Prehistory, Autonomous University of Barcelona,
Barcelona, Spain. 2 Independent researcher, Spain.

[oriollopezbulto\@gmail.com](mailto:oriollopezbulto@gmail.com){.email}

It is suggested that woodland management (e.g. pollarding, pruning or
coppicing) was practised at least from the Neolithic onwards. The goal
of this presentation is to discuss woodland management practices in the
Early Neolithic waterlogged site of La Draga (5300-4700 cal BC -
Banyoles, Spain). So far different methods and techniques
(dendrochronology, roundwood age and diameter, dendrology...) have been
applied to approach this issue and some preliminary results obtained.
But recent excavations brought forth new wooden archaeological materials
which help approach this issue from another point of view: the presence
of scars on the wood surface. For the first time, at la Draga, it has
been possible to identify scars on the wood surface of piles caused
after tool-marks and covered partially or totally by woundwood ribs,
indicating that the trees were marked before being cut down. The piles
marked have been identified as laurel (Laurus nobilis), this taxon is
well documented at the site (firewood, instruments and piles), although
playing a secondary role after oak. However, laurel is a tree rarely
exploited during the Neolithic in Europe, which poses the question of
the intentional selection of this wood at La Draga. This paper will
present the results of the morphological, technological and
dendrological study of the laurel piles in the context of the wooden
remains of La Draga site. The results of the different approaches are
summarized and contrasted to provide new lights on Neolithic woodland
management in Europe. Moreover, it is discussed the role of the laurel
tree in the context of the Neolithic.

## S1-O-007 {.unnumbered}

**From the exhaustive study of a mountain village to the restitution of
forest: how far can dendrochronology go?**

Lisa Shindo1

1 ROOTS Cluster of Excellence, Institute of Pre- and Early Prehistoric
Archaeology, Christian-Albrechts-University, Kiel, Germany.

[lshindo\@roots.uni-kiel.de](mailto:lshindo@roots.uni-kiel.de){.email}

Since 2014, as part of several research projects on the links between
humans and forests in the past, 20 buildings in a village in the
southern French Alps (Courbons, 900 m altitude) have been studied by
dendrochronology. These are mainly village houses but also a church, a
bell tower and a mill. We were interested in the wood used in the
structural work, which is only present in the ceilings. These are mostly
joisted, but two of them are more elaborated, with visible beams and
joists. A total of 155 timbers were studied. The species used are very
varied, oak, fir, larch, Scots pine, elm, ash and willow or poplar, as
are the growth patterns and felling dates, which range from the 14th to
the 19th century. Although the village is mentioned in texts as early as
the 12th century, the main felling phases take place in the 15th and
18th centuries (the study of these timbers contributed to the
construction of the first oak reference curve at altitude in the
southern French Alps). According to the texts, since at least the 15th
century, local wood has been exported to the lowland cities and is at
the heart of a very active local market. As we have observed a change in
the wood used in the 16th c., we will address the issues of wood
resources and forestry management in this region at the crossroads of
several trade routes, linking the high mountains, the plains and the
Mediterranean Sea.

## S1-P-001 {.unnumbered}

**Our history does not exist in the books: forest patches framing new
identities for heritage and environmental conservation**

Pascoal Gota1, Anneli Ekblom1

1Department of Archaeology and Ancient History, Faculty of Arts, Uppsala
University/ Uppsala, Sweden.

[pascoal.gota\@arkeologi.uu.se](mailto:pascoal.gota@arkeologi.uu.se){.email}

With the huge increase of illegal logging activities globally, forests
that are not in the borders of officially designated conservation areas
are currently at risk of being classified, simplified and reduced to
spaces for logging. In the best case scenario, these forests can be
spared either through conservation protection (which tends to exclude
local communities) or through a re-categorisation as sources for
ecosystem services of benefit for several stakeholders. Forest patches
play a fundamental role in ensuring the existence of several ecosystem
services. In this paper we bring into discussion the results of field
work carried in two of the several forest patches located in southern
Mozambique. Methodologically, we approach forest patches as cultural
landscapes and heritage sites. Our aim is to formulate an approach of
biodiversity conservation that goes beyond officially protected areas,
such as parks and reserves in collaboration with local communities
through the notion of protected cultural landscapes and bicultural
heritage. In doing so, we documented the histories of these forest
patches as embedded in social memories and physical remains (pollen,
charcoal and archaeological finds) to narrate the role of forest mosaics
in shaping the identity of current communities. With our findings, we
illustrate that the local conservation of these forests is effective,
resting on tangible and intangible protection of heritage a practice
fundamental for the identity of custodian communities. We conclude by
providing some insights for the study and understanding of
transdisciplinarity and conservation as these protected forests are
potential bridges to dialogue and community-based heritage-conservation
initiatives through collaborative approaches to achieve several of the
sustainable development goals.

## S1-P-002 {.unnumbered}

**Mechanical wood properties over the past 100 years**

Andreas Rais1, Andriy Kovryga1, Jan-Willem G. van de Kuilen1,2

1 Materials Engineering, School of Engineering and Design, TU Munich,
Munich, Germany. 2 Engineering Structures, Biobased Structures and
Materials, TU Delft, Delft, the Netherlands.

[rais\@tum.de](mailto:rais@tum.de){.email}

Forest stands adapt their growth on changes of temperature, nitrogen
deposition, CO2-concentration and growing season. Forest management
strategies also influence tree growth, for instance by admixing
deciduous trees in coniferous forests or reducing rotation age and stand
density. Climate change by itself or indirectly through silvicultural
adaptations may have influenced the wood (mechanical) properties. The
focus of this study is on Norway spruce (Picea abies), which is relevant
for use in construction despite the climate and calamity-related decline
in European forests. Our internal database contains data about strength,
stiffness, density and knot parameters from more than 10.000 boards.
Most of the data were collected in order to derive models and threshold
values for structural engineering applications, and as such can be
considered representative of the timber grown in Central Europe in the
last two centuries. From each of these boards, a small, defect-free wood
sample is available to determine the date of wood formation
(dendrochronological approach) and essential growth ring
characteristics. The presentation highlights the methods, but also gives
first insights into whether mechanical wood properties may have changed
in the last century. Changes in wood quality due to climate and
management concepts are important for the entire wood processing chain
forest-sawmill-final product. As the log and wood quality determine the
product performance, any changes have a direct impact on the production
chain and the added value during each production step. Sawmills notice a
change in timber quality due to changed yields in the various
assortments that they produce affecting revenue.

## S1-P-003 {.unnumbered}

**Dendrochronological investigation of monumental trees from "Villa
Medicea di Castello" in Florence, Italy**

Sveva Longo1, Cristiano Riminesi1, Rachele Manganelli del Fà1, Silvia
Fineschi1, Giovanna Battipaglia2 1 Institute of Heritage Science,
National Research Council of Italy, Italy. 2 Department of
Environmental, Biological, Pharmaceutical Sciences and Technologies,
University of Campania "Luigi Vanvitelli", Caserta, Italy.

[sveva.longo\@ispc.cnr.it](mailto:sveva.longo@ispc.cnr.it){.email}

The garden of the Villa Medicea of Castello was designed by Niccolò
Tribolo in 1538 on commission of Cosimo I de' Medici, Gran Duke of
Florence, and represents one of the prototypes of the XVI century
Italian garden. A cycle of 'lunettes' painted by the Flemish artist
Iustus van Utens between 1599 and 1603 illustrate fourteen villas
belonging to the Medici Family, including this one. In this study, we
performed dendrochronological analysis on two pubescent oaks, Quercus
pubescens Willd, from the "Piano del selvatico", to verify whether they
might be dated back to the garden origin. This analysis would provide
important information on the vegetation history of the garden, and fill
lack of records about its past management. Two trees, ranging in size
from 100 to 150 cm diameter at breast height, were sampled. Two cores
for each plant were collected in summer 2021 using an increment borer
(Haglöfs, Sweden) of 5 mm. Results revealed that both trees show evident
signs of senescence, with rotting of the wood in the central part and
have undergone several pest attacks during their existence. It was not
possible to reach the center of the trunk due to the presence of rotten
wood, therefore the missing rings were estimated by allometric equation
to define the age of the two oaks. The age was determined about 500
years old. The estimated age of two pubescent oaks allows us to affirm
that they were already present when the 'lunettes' were painted.

## S1-P-004 {.unnumbered}

**History of wood management**

Caroline Vermeeren1, Kirsti Hänninen, Welmoed A. Out2 1 BIAX Consult,
Research centre, Zaandam, the Netherlands. 2 Moesgaard Museum, Aarhus,
Denmark.

[vermeeren\@biax.nl](mailto:vermeeren@biax.nl){.email}

From written and iconographic sources there is proof for wood management
in the historical period, but when did this practice start? It is often
assumed that this could have been as far back as the Neolithic. To
investigate this, a model was made using the combination of diameter and
number of annual rings (figure 1). Management (pollarding and coppicing)
results in a higher quantity and quality of wood, due to better access
to light. Managed trees are supposed to grow faster, producing thicker
annual rings. This was tested on modern trees resulting in reference
graphs per taxon. Case studies for the Neolithic from different parts of
Europe, are compared to these graphs of which some will be presented. A
management signal could not be found. Different possibilities are
discussed to explain this result.
