# Session 2: Shipwrecks and archaeological structures {.unnumbered}

## S2-O-001 {.unnumbered}

**Piers, wharfs and shipping at Masthugget, Gothenburg -- Investigating private harbours through wood and stone structures**

Andrine Nilsen1

1 Rio Göteborg Natur- & kulturkooperativ, Gothenburg, Sweden.

[andrine.nilsen\@riogbg.se](mailto:andrine.nilsen@riogbg.se){.email}

The harbour area Masthugget have large timber collections and stone structures as its main archaeological features. This contract archaeological project investigates how the built environment changes in character in different parts of the harbour from enterprise oriented to large private estates with lush gardens. The dendrochronological analysis is of vital importance to the project linked to dating, wood provenance analysis, the inquiry into timber supplies as well as for the study of the reconstruction and development of the harbour. Dendrochronology also plays part in the dating of the building stock on the piers and plots. Other dating tools used to track the 17-19th century are archaeological finds analysis combined with historical maps of the area. Most plots and piers were private, and the owners were to a high degree well-known tradesmen many with Scottish origin. The city also owned two of the piers, one used as an iron-weighing station. In many ways, the harbours expands and benefits from international trading blockades connected to wars between England, France and North America affecting the colonial trade. The harbour was used for the import of colonial goods while exports such as tea, herring, iron and whale-oil were the most important. Other significant exports were timber and masts (which gave the harbour its name). The project aims to find out how this foremost private harbour changed over time, how it was used, what the building stock of the piers looked like and how the buildings connected to the various enterprises of the area.

## S2-O-002 {.unnumbered}

**Marking time in the Iron Age; the dendrochronology of loch (lake) settlement in SW Scotland**

Anne Crone1

1 AOC Archaeology Group, Unit 7A Edgefield Industrial Estate, Loanhead, Midlothian, Scotland.

[anne.crone\@aocarchaeology.com](mailto:anne.crone@aocarchaeology.com){.email}

Although there is evidence for settlements in the lochs of Scotland from the Neolithic to the early modern period, the 1st millennium BC saw the most intense period of activity, specifically that period from 800 to 400 BC where the calibration curve is so flat as to render radiocarbon determinations highly imprecise. Studies of the Iron Age throughout Europe are bedevilled by the Halstatt Plateau but in the British Isles few sites of that period have benefitted from the precision of dendro-dating. However, in a small area of SW Scotland, there are now three dendro-dated wetland settlements which are enabling archaeologists to examine the dynamics of regional settlement development via the chronological relationships between these sites. Extensive excavations at one of these sites, Black Loch of Myrton, yielded large quantities of oak, alder, hazel and ash, all of which have been analysed to produce a precisely dated chronological framework spanning three major episodes of occupation on the settlement, from 438/7 BC to 223 BC. Over the course of two centuries we see the development, expansion, abandonment and re-occupation of the settlement, all at the scale of human lifetimes. In this talk the dendrochronological evidence from SW Scotland will be outlined, and some of the interpretative issues associated with the use of non-oak species will be raised. The impact of high-resolution timescales on our understanding of the dynamics of settlement in this period will also be explored.

## S2-O-003 {.unnumbered}

**Just bad quality? Some thoughts on the use of timber in medieval to modern shipbuilding**

Mike Belasus1

1 Lower Saxony Institute for Historical Coastal Research, Wilhelmshaven, Germany.

[belasus\@nihk.de](mailto:belasus@nihk.de){.email}

The perception of wood in connection to shipbuilding of the past seems to be strongly idealised and often not fitting to the reality reflected in the archaeological context. Features of tree-anatomy were only sometimes recorded, and often ignored during the interpretation of ship finds. The idealized idea of a shipwright, who is choosing personally only the best material, was likely born out of an idealized image of the past and possibly influenced by rather recent shipbuilding practices. Detailed advise on the choice of high quality timbers for shipbuilding only appear in the 20th century, long after wood was superseded by steel for most vessels and competition for shipbuilding timber on the marked market had ceased. In some cases, this has produced a somewhat distorted interpretation of ships and shipbuilding because features of growth, in a holistic approach, can give information beyond timber quality but also on environmental influences and the human impact on this resource. In certain cases, it even allows to draw conclusions on economic and social circumstances. This way the information gathered from the building timber can alter the vessels interpretation. This paper will discuss the demands for shipbuilding timber and its quality in North Western Europe as a result of the ERC-TIMBER project (Grant agreement No. 677152). It aims to reflect on possible social, economic or environmental reasons for the shipwrights' choices.

## S2-O-004 {.unnumbered}

**Double checking double Dutch: A reassessment of the construction features of the early modern Scheurrak SO1 shipwreck**

Rik Lettany1 , Petra Doeve2, Esther Jansma3

1 Department of World Archaeology, Faculty of Archaeology, Leiden University, Leiden, the Netherlands. 2 BAAC Archeologie en Bouwhistorie. 3 Cultural Heritage Agency of the Netherlands.

[h.lettany\@arch.leidenuniv.nl](mailto:h.lettany@arch.leidenuniv.nl){.email}

In 1984, the remains of a late 16th Century Dutch merchantman were discovered off the coast of Texel, the Netherlands. The excavation of the site, named Scheurrak SO1 after its location, started in 1988 and ended in 1997. With a strong focus on the ship's construction features, it became one of the pioneering projects of Dutch underwater archaeology. The shipwreck exhibited several peculiar construction details which deviated from other contemporary European shipbuilding traditions. As such, the data recovered from the Scheurrak SO1 shipwreck contributed strongly to what in nautical archaeology became known as the Dutch Flush and the Double Dutch discourses. Dutch flush refers to the shell-first building sequence of Dutch carvel built ships, at a time that most shipbuilding traditions used a frame-first sequence. Double Dutch, then again, refers to a brief moment in time when Dutch flush ships were built with a double layer of planking. Scheurrak SO1 has been considered the earliest known example of this latter technique. Based upon very limited dendrochronological data, the initial hypothesis was that Scheurrak SO1 was built around 1580 with two layers of planking. Reassessment of Scheurrak SO1's construction details within the frame of the interdisciplinary research project "Scheurrak SO1 in the Maritime Cultural Landscape of the Early Modern Netherlands, 1550-1650" at Leiden University, now suggests that the ship may have known multiple building phases. Re-analysis of the available tree-ring curves seems to support this, while analysis of additional samples demonstrate a more dispersed timber provenance than initially deduced. Although research is still ongoing, current results do challenge the known Double Dutch discourse and encourage a reinterpretation of the construction of the Scheurrak SO1 shipwreck.

## S2-O-005 {.unnumbered}

**From a forest to a ship and into a wreck, and back again?**

Minna Koivikko1, Tuomas Aakala2, Katariina Vuori3

1 Finnish Heritage Agency, Finland. 2 Department, Jyväskylä, Finland. 3 Department, Oulu, Finland.

[minna.koivikko\@museovirasto.fi](mailto:minna.koivikko@museovirasto.fi){.email}

The aim of the project is to develop interpretation of so-called skeleton wrecks, i.e., wooden wrecks, which only have preserved partly, and no informative objects have been discovered. We are studing the relationship between a man and a forest through interpretation of wooden vessels. The Lost Navy, Sweden's "Blue" Heritage c. 1450--1850 research programme aims to collect information about the ships in the fleet. It is a joint marine archaeology and - history project in the Baltic Sea region for 2021--2026. In Finland, the research sub-project focuses on wooden wrecks of the Swedish era fleet. The project has a multidisciplinary approach, combining archaeology with shipbuilding, dendrochronology, and forest studies.

## S2-O-006 {.unnumbered}

**Wood identification and dendrochronological techniques applied for the study of shipwrecks on the Atlantic coast of Argentina: comparison of different case studies showing limitations and potentials**

Ignacio A. Mundo1,2

1 Laboratorio de Dendrocronología e Historia Ambiental, IANIGLA/CONICET, Mendoza, Argentina. 2 Facultad de Ciencias Exactas y Naturales, Universidad Nacional de Cuyo, Mendoza, Argentina.

[iamundo\@mendoza-conicet.gob.ar](mailto:iamundo@mendoza-conicet.gob.ar){.email}

Wood anatomy or xylogeny allows the botanical identification of woody material based on the recognition and quantification of various wooden traits. In the case of archaeology, and in particular for nautical archaeology, the wood anatomy provides information on the possible origin of nautical structures based on the range of distribution of woody plants, allows the association between the function fulfilled by a piece within a vessel and the mechanical properties of the wood, and it also helps to evaluate aspects related to the availability of timber and the building technology of a shipwreck, among others. In a nautical archaeological sense, dendrochronology analyses the information recorded in tree rings of timbers, which allows the dating of woody materials used in ship building, as well as estimating their possible origin (i.e. dendroprovenancing). In this context, the interdisciplinary work between these three disciplines (xylogeny, dendrochronology and nautical archaeology) has only recently been applied in Argentina, despite the existence of a large number of woody nautical remains on the extensive Atlantic coast of this country. Through the analysis of different case studies carried out in the last years, this presentation aims to present and discuss the scope and limitations of the wood anatomy analyses in underwater archaeological studies in Argentina as well as to emphasize the dendroarchaeological potential of some of the materials found. The characteristics of the materials analysed in each case will be summarised, highlighting the limitations encountered and the potentialities for future studies.

## S2-O-007 {.unnumbered}

**House and Boat. Reuse of ship planking in a 10th century building at Hungate, York**

Steven J. Allen1

1 Conservation Department, York Archaeology.

[sallen\@yorkat.co.uk](mailto:sallen@yorkat.co.uk){.email}

In the course of excavations by York Archaeological Trust (Now York Archaeology) in 2008-9 at Hungate in York revealed the waterlogged timbers of another building of a type best known from Coppergate. This building, dating to the third quarter of the 10th century CE was superficially of the same construction as seen earlier at Coppergate and was a rectangular pit cut into the ground, lined with posts that supported a boarded outer lining. At Coppergate, the timbers were largely freshly felled specifically for the buildings in which they were found and the tree ring sequences are local to the York region. However at Hungate, when the timbers were lifted, it was immediately apparent that the board lining was in fact made up of reused articulated slabs from a clinker-built boat. Moreover, the type of clinker construction was unusual and not of the 'typical' North West European/Scandinavian type. Dendrochronological samples allowed the identification of the potential source for the boat timbers, which was not local to York. This paper considers the evidence provided from the study of the woodworking technology and the work done to identify the type of boat, its potential provenance and indeed the provenance of the timbers used in its construction.

## S2-O-008 {.unnumbered}

**How a broken wooden board uncovered an early medieval mill**

Julia Weidemüller1, Franz Herzig1, Leander Schmidt1, Jeremy Collacott1

1 Bayerisches Landesamt für Denkmalpflege, Thierhaupten, Germany.

[julia.weidemueller\@blfd.bayern.de](mailto:julia.weidemueller@blfd.bayern.de){.email}

In September 2021, historic timbers were uncovered at a construction site in Aichach, Bavaria. The site was not designated as monument, therefore it was not accompanied archaeologically. Nevertheless, the construction company reported these finds to the Bavarian State Office for Monument Preservation (BLfD). The first pieces were examined in the internal laboratory for dendroarchaeology. The site could be identified as an early medieval mill on the basis of a broken paddle fragment. Subsequently, hundreds of timbers from several construction phases of the mill were excavated and documented in close cooperation between Construction Company, Archaeological Specialists and Dendroarchaeologists. In addition to small finds such as paddles, vessels and tools, numerous construction timbers were found, many still in situ. For the first time, an intact mill pond, including dam, filter system and mill channel, could be excavated. In this case the wood species composition is exciting, since a large part of the construction timbers consisted of alder and beech. Only heavily used structures like the sluice gate or the substructures of the mill building were made of oak. The investigations have not yet been completed. First measurements date to the 8th and 9th centuries AD. A heavy flood event ended milling at this site. A comprehensive archaeological evaluation is planned, including age structures and wood species composition. However, the sheer mass of the timbers would offer many more starting points for statistical analyses on early medieval forest structures and wood species selection, to name a few. Since there are no resources available at BLfD for research of this kind, I hope that the presentation of the project to expert circles will provide helpful comments and possibly lead to further research.

## S2-O-009 {.unnumbered}

**A dendroarchaeological study of Roman-period river barges from the Lower Rhine region**

Yardeni Vorst1

1 Vorst wood research, Zaandam, the Netherlands.

[yvorst\@gmail.com](mailto:yvorst@gmail.com){.email}

In 2003, a river barge dating to the Roman period was found in a former riverbed of the Rhine in the western part of the Netherlands. The ship, named 'Woerden 7', formed a new discovery in a long series of Roman-period ship finds in Lower Rhine region since the late 1960's. In particular, large flat-bottomed river barges had been found. Many of these vessels were excavated and some were conserved, such as the The Zwammerdam ships, found in the village of Zwammerdam in the 1970's. For a research project these ships have been re-examined using more modern techniques. A comparison between ship Zwammerdam 6 and the earlier mentioned Woerden 7 vessel shows that the ships resemble each other closely in construction. Apart from a study of the ship constructions a dendroarchaeological study of the timbers has been undertaken. Dendrochronology has been used to date the ships and to determine which timbers were obtained from the same trees. This has helped to trace original building sequences and allowed for new ideas on the shipbuilding processes. Identifying the source area of trees used in this Roman-period shipbuilding, i.e. the provenance of the timbers will be presented in an other paper together with Ronald Visser. The Zwammerdam vessels are currently being reconstructed at an archaeological park (Archeon) in the South of Holland and the research information gathered will contribute to stories on their historical background.

## S2-P-001 {.unnumbered}

**Conservation processes of a painted wooden coffin at Saqqara area**

Abdelmoniem M. Abdelmoniem1 , Naglaa Mahmoud1, Wael S. Mohamed2,

1Conservation Department, Faculty of Archaeology, Fayoum University, Fayoum, Egypt. 2 Polymer department, National Research Centre, Dokki, Giza, Egypt.

[ama63\@fayoum.edu.eg](mailto:ama63@fayoum.edu.eg){.email}

This paper aims to document the conservation processes of a polychrome wooden coffin at Saqqara dating back to the late period. The exterior part of the coffin is decorated with painted layer, while inside it is covered with a layer of the black resin. The coffin was in a bad condition. It was covered with a thick layer of dust, loosing parts of the painted and gesso layers, as well as other parts of these layers were lost. Some parts were missing from the foot area of the lid coffin. 2D illustrations and 3D modules were made to document the coffin. The conservation processes of the wooden coffin included mechanical and chemical cleaning, reattachment of the separated parts of the ground layer and painted layers, filling the edge of the painted layer, and consolidating the black resin layer. The materials used for these processes proved to be stable and retrieval by many researchers. The conservation process included mechanical cleaning using soft brushes, chemical cleaning using ethyl alcohol and water for painted layer and xylene and water for black resin layer, stabilization of the separated gesso layer using Paraloid B72, filling cracks of the gesso layers using glass microballoon with Paraloid B72, and consolidating the painted layer with KlucelE and black resin layer with Nano Paraloid B72.

## S2-P-002 {.unnumbered}

**Microscopy techniques for the examination of waterlogged archaeological wood**

Angela Balzano1, Maks Merela1, Katarina Čufar1

1 Biotechnical Faculty, University of Ljubljana, SI1000 Ljubljana, Slovenia.

[Angela.Balzano\@bf.uni-lj.si](mailto:Angela.Balzano@bf.uni-lj.si){.email}

Waterlogged archaeological wood (WAW) from prehistoric pile-dwelling settlements in Ljubljansko barje, Slovenia, was examined using various microscopic techniques. We have performed light microscopy (LM) using bright field, polarization and fluorescence modes with different sample preparation methods (cutting of frozen WAW, cutting after embedding in paraffin). Unstained and stained sections with safranin and astra blue or acridine orange and chrysoidin were considered. We have developed an improved protocol for scanning electron microscopy (SEM) and energy dispersive X-ray spectroscopy (EDX) based on the observation of sections obtained with a razor blade from frozen samples and fixed with albumin on sample supports to prevent cracking and collapse of the highly degraded wood. Advantages of applied techniques will be shown for WAW of Quercus, Faxinus, Acer, Salix and Populus with an age of about 4,500 years. Sections from frozen WAW, approximately 20-30 µm thick and 1cm2 in size, allowed recognition of cellular and tissue level structures with LM. Embedding in paraffin provided thinner but smaller sections which tended to tear. The improved SEM protocol provided high quality images of large sections at lower magnifications and also of details at high magnifications with high resolution. The combination of SEM and EDX allowed the observation of the preservation of the cell wall as well as the location, amount, shape and chemical composition of various inclusions with high amounts of Fe, S and Ca found in all taxa studied, while Populus also contained increased amounts of Si.

## S2-P-003 {.unnumbered}

**Practices of shipwreck timber sampling for dendrochronology**

Daniel Peter Dalicsek1

1 Moesgård Museum, Aarhus, Denmark.

[dad\@moesgaardmuseum.dk](mailto:dad@moesgaardmuseum.dk){.email}

In 2018, two important publications saw light, Selecting and Sampling Shipwreck Timbers for Dendrochronological Research: practical guidance by Daly et al. and Shipwrecks and Provenance: in-situ timber sampling protocols, with a focus on wrecks of the Iberian shipbuilding tradition by Rich et al. My presentation would look at the impact of these publications and the focus on the works of maritime archaeologists and dendrochronologists in sampling shipwreck timbers over the past five years. It´s main focus would be on intrusive survey methods and on shipwreck sites, but would not exclude other underwater sites or terrestrial excavations. It would consist of a survey questionnaire, sent out to maritime archaeologists across the globe and interviews with maritime archaeologists and dendrochronologists ahead of the conference. This would enable insight and provide an overview over fieldwork practices today. The presentation would showcase the opportunities for better and more uniform sampling practices as well as present a chance for and generate discussion among the conference´s audience. The aim is to take a snapshot of how we conduct our science and if collaboration between dendrochronologists and archaeologists is sufficient.

## S2-P-004 {.unnumbered}

**The Gribshunden Barrels**

Anton Hansson1, Hans Linderson1, Brendan Foley2

1 The Laboratory of Wood Anatomy and Dendrochronology, Department of Geology, Lund University, Lund, Sweden. 2 Department of Archaeology and Ancient History, Lund University, Lund, Sweden.

[anton.hansson\@geol.lu.se](mailto:anton.hansson@geol.lu.se){.email}

The Danish Royal Flagship Gribshunden sank in the Blekinge archipelago in the early summer of 1495, while on its way to the Swedish town of Kalmar. There the Danish King Hans planned to meet the Swedish Regent Sten Sture the Elder in the kings wish to re-establish the Nordic Union between Denmark, Norway, and Sweden by being elected king of Sweden. During field campaigns in 2019 and 2021 a joint multi-disciplinary research effort led by Lund University has excavated parts of the Gribshunden shipwreck. As a part of the excavations, a large number of barrels staves and heads were recovered for dendrochronological and dendroprovenance analysis in order to answer certain research questions: (i) the timber source area (ii) The barrel construction locality (iii) the lifespan of a barrel (iiii) barrel size and standards. In total, 135 oak staves and heads were analysed, 79 % of which were successfully dated. Two major timber source areas were revealed, Baltic (59%) and Scania (22%). The mix of timber sources in the barrels suggest they were not constructed in the source area. Based on the average sapwood amount we can conclude that most barrels must have been constructed a few years prior to sinking, suggesting a short life span of barrels in general. Together with these dendrochronological results, further studies on numerous finds at the wreck site will provide new views of the medieval economy and political connections in the late medieval period.

## S2-P-005 {.unnumbered}

**Connecting ships: using dendrochronological network analysis to determine provenance and ship building practices of Roman-period river barges found in the Lower Rhine region**

Ronald M. Visser1, Yardeni Vorst2

1 Archaeology, School of Business, Building and Technology, Saxion - University of Applied Sciences, Deventer, Netherlands. 2 Vorst wood research, Zaandam, the Netherlands.

[r.m.visser\@saxion.nl](mailto:r.m.visser@saxion.nl){.email} - [yvorst\@gmail.com](mailto:yvorst@gmail.com){.email}

Over the past decades various Roman-period river barges were found in the Lower Rhine region. These ships were large vessels of over twenty meters in length. Many were excavated in order to document the constructions and some were lifted from the ground and conserved for future display. The first barges that were found (fifty years ago), the Zwammerdam ships, were among those that were preserved. This has more recently allowed for a re-examination of their ship constructions using more modern techniques. Research on the constructions including a dendroarchaeological study of the timbers has been undertaken by Y. Vorst. The provenance of the wood has been studied by both researchers, based on a recently published approach (Visser 2021). This approach uses networks to visualize and explore dendrochronological relations based on similarity. In addition, these networks give insight in other aspects of ship building practices, such as wood use and the construction. The combined studies have led to a better understanding of past practices in shipbuilding and timber transport and use during the Roman period.

Visser, RM. 2021 Dendrochronological Provenance Patterns. Network Analysis of Tree-Ring Material Reveals Spatial and Economic Relations of Roman Timber in the Continental North-Western Provinces. Journal of Computer Applications in Archaeology 4(1): 230--253. DOI: <https://doi.org/10.5334/jcaa.79>.
