# Session 8: Not assinged to session yet {.unnumbered}


## S?-O-00x {.unnumbered}

**Old Wood in a New Light -- A dendrochronological database**

Johannes Edvardsson^1^, Philip Buckland^2^, Anton Hansson^1^, Mattias Sjölander^2^, Johan von Boer^2^, Hans Linderson^1^, Björn Gunnarson^3^, Hans W Linderholm^4^, Igor Drobyshev^5^, Björn Nilsson^6^, Dan Hammarlund^1^

*^1^ Laboratory for Wood Anatomy and Dendrochronology, Department of Geology, Lund University, Lund, Sweden. ^2^ The Environmental Archaeology Lab and the Strategic Environmental Archaeology Database (SEAD), Umeå University, Umeå, Sweden. ^3^ Department of Physical Geography, Stockholm University, Stockholm, Sweden. ^4^ Department of Earth Sciences, University of Gothenburg, Gothenburg, Sweden. ^5^ Southern Swedish Forest Research Centre, The Swedish University of Agricultural Sciences (SLU), Alnarp, Sweden. ^6^ Department of Archaeology and Ancient History, Lund University, Lund, Sweden.*

<johannes.edvardsson@geol.lu.se>

The Old Wood in a New Light project focusses on digitisation and accessibility of the results of dendrochronological samples analysed and archived at the four Swedish university-based tree-ring laboratories located at Lund University, Stockholm University, University of Gothenburg, and the Swedish University of Agricultural Sciences. Collaboration with the Environmental Archaeology Laboratory and Humlab at Umeå University will enable long-term open access to data and metadata. In this project, we will (1) systematically undertake large-scale entry and open access publication of results from scientifically analysed and archived wood samples in Sweden, and their associated metadata, into the SEAD research data infrastructure (Strategic Environmental Archaeology Database; www.sead.se), and (2) actively promote the database as a resource for new and ongoing interdisciplinary research initiatives. Inclusion of dendrochronological data in the SEAD infrastructure will allow for multidisciplinary studies combining major scientific and societal questions. SEAD is already adapted to this purpose, a pilot study has been undertaken and digitisation workflows and time estimates have been confirmed for the more than 70,000 samples archived at the Lund University dendro laboratory, where the project is hosted, and its partners. Broad coverage of research networks, stakeholder interaction and strategic support from the cultural heritage community are guaranteed by the project partners and an established international and multidisciplinary reference group.